Project_11/urls.py
from django.contrib import admin
from django.urls import path, include
import app1, app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
]

app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'

urlpatterns=[
    path('First/', First, name='First'),
    path('Second/', Second, name='Second'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('Third/', Third, name='Third'),
    path('Fourth/', Fourth, name='Fourth'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def First(request):
    return render(request, 'first.html')

def Second(request):
    return render(request, 'second.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def Third(request):
    return render(request, 'third.html')

def Fourth(request):
    return render(request, 'fourth.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>First</title>
</head>
<body>
    <center>
        <h1>This is 1st Html Page</h1>
    </center>
    <h1><a href="{% url 'app1:Second' %}">Navigate to Second</a></h1>

    <h1><a href="{% url 'app2:Third' %}">Navigate to Third</a></h1>

    <h1><a href="{% url 'app2:Fourth' %}">Navigate to Fourth</a></h1>
</body>
</html>

templates/fourth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fourth</title>
</head>
<body>
    <center>
        <h1>This is 4th Html Page</h1>
    </center>
    
    <h1><a href="{% url 'app1:First' %}">Navigate to First</a></h1>

    <h1><a href="{% url 'app1:Second' %}">Navigate to Second</a></h1>

    <h1><a href="{% url 'app2:Third' %}">Navigate to Third</a></h1>
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Second</title>
</head>
<body>
    <center>
        <h1>This is 2nd Html Page</h1>
    </center>
    <h1><a href="{% url 'app1:First' %}">Navigate to First</a></h1>

    <h1><a href="{% url 'app2:Third' %}">Navigate to Third</a></h1>

    <h1><a href="{% url 'app2:Fourth' %}">Navigate to Fourth</a></h1>
</body>
</html>

templates/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Third</title>
</head>
<body>
    <center>
        <h1>This is 3rd Html Page</h1>
    </center>
    
    <h1><a href="{% url 'app1:First' %}">Navigate to First</a></h1>

    <h1><a href="{% url 'app1:Second' %}">Navigate to Second</a></h1>

    <h1><a href="{% url 'app2:Fourth' %}">Navigate to Fourth</a></h1>
</body>
</html>